default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chopbill_be_development

test:
  <<: *default
  database: chopbill_be_test

production:
  <<: *default
  database: <%= ENV["CHOPBILL_BE_DATABASE_NAME"] %>
  username: <%= ENV["CHOPBILL_BE_DATABASE_USERNAME"] %>
  password: <%= ENV["CHOPBILL_BE_DATABASE_PASSWORD"] %>
  host: <%= ENV["CHOPBILL_BE_DATABASE_HOST"]%>
  port: 5432
